### ISSUE TITLE
Archipelago with fitness calculated by OpenCL GPGPU

### ISSUE THREAD

**Issue by pradyparanjpe** [esa/pagmo2#374] opened 2019-12-17 15:11 UTC
I have a GPGPU calculation problem coded in OpenCL. (Naturally,) this cannot be calculated on a CPU.

I define a udp in pygmo, whose fitness function:
`def fitness(self,x):
    obj = eucl_cl((target, x, self.dim))`

calls a python3 wrapper, `eucl_cl(args)` that:
uses pyopencl to discover platforms,
compile the OpenCL program,
pass the buffers, etc.
and return the calculation result
to be minimized.

A serial implementation of a similar wrapper `eucl_ser(args)` called by udp fitness function works without error.

The OpenCL program is separately tested OK.
(pyopencl wrapper called asynchronously by module multiprocess.pool)
`r = pool.map_async(eucl_cl, (target, x, dims))`
`res = r.get()`

However, the execution throws error "Segmentation fault (core dumped)" when archipelago is initiated with pyopencl wrapper fitness

(at the line in the wrapper where pyopencl discovers GPGPU platforms).
`plat = cl.get_platforms()`
`# Seg Fault before HERE`

Is there a way where pygmo calls a wrapper that executes some calculation on OpenCL platform?
Will translating the python3 code to Cpp (using opencl and pagmo) help?

**Comment by bluescarni** [comment] 2019-12-17 19:50
@pradyparanjpe does the segfault happen during the initialisation of the archipelago or during evolution? Also, what pygmo version is this and which platform? Are you using binary packages or did you compile pygmo yourself?

**Comment by pradyparanjpe** [comment] 2019-12-18 04:02
1) Segfault during initialization of archipelago.
`archi = pg.archipelago(n=4, algo=algo, prob=prob, pop_size=32)`

2) A) `uname -a`
Linux ekadanta-fc31.anubandha 5.3.15-300.fc31.x86_64 #1 SMP Thu Dec 5 15:04:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
B) `clinfo`
...
OpenCL 1.1 Mesa 19.2.7
...
AMD OLAND (DRM 2.50.0, 5.3.15-300.fc31.x86_64, LLVM 9.0.0)
...
I'm coding it on my personal laptop, but will implement it on a hybrid cluster.

3) I installed pygmo using `pip install --user pygmo`
matplotlib, numpy, multiprocessing, etc. regular python modules are managed by fedora's dnf package manager.
Would compiling pygmo it locally help?

**Comment by bluescarni** [comment] 2019-12-18 09:58
Just to rule out a potential problem with the ``pip`` packages, would it be possible for you to try with the conda packages instead?

The fact that ``pop = pg.population(prob=prob, size=32)`` segfaults too indicates that probably this is not an issue related to threading/parallel processing, as the the population class does not make use of any of that.

One thing to keep in mind is that populations, archipelagos, etc., all make deep copies of the input problem. Perhaps the problem is there? Does deep-copying and/or pickling your user-defined problem work?

**Comment by pradyparanjpe** [comment] 2019-12-18 10:49
Update.

I compiled pygmo locally.
The segfault was solved.

Thanks.

**Comment by bluescarni** [comment] 2019-12-18 12:10
Good to hear it got solved by a recompilation. I'll close the issue then.

Would it be possible for you to paste here (or elsewhere) a minimal example exhibiting the segfault? It would be helpful for us in order to investigate where the problem might originate from.

**Closed by bluescarni** 2019-12-18 12:10 UTC
