### ISSUE TITLE
Bounds for control parameters (PSO)

### ISSUE THREAD

**Issue by Hvass-Labs** [esa/pagmo2#210] opened 2018-08-17 14:49 UTC
Hello,

Thanks very much for making this library!

I want to use the PSO optimizer and set my own control parameters, but you have some very restrictive bounds on the parameters and I get these errors:

	ValueError: 
	function: pso
	where: /usr/local/include/pagmo/algorithms/pso.hpp, 185
	what: The particles' inertia (or the constriction factor) must be in the [0,1] range, while a value of -0.5 was detected

and:

	ValueError: 
	function: pso
	where: /usr/local/include/pagmo/algorithms/pso.hpp, 190
	what: The eta parameters must be in the [0,4] range, while eta1 = -1.6, eta2 = -3.5 was detected

Please see this short paper for examples of PSO parameters that are outside your allowed bounds: http://hvass-labs.org/people/magnus/publications/pedersen10good-pso.pdf

I can't find the file `/usr/local/include/pagmo/algorithms/pso.hpp` so I can't change these bounds myself. Is the file located somewhere else?

Can you change or disable the parameter bounds in the official release? How often do you put out new releases?

----

I have a few general comments about pygmo that may be useful to you.

I used NSGA-2 from pygmo / pagmo for a project I just did. It takes a while to get used to the API but then it worked really well:

https://github.com/Hvass-Labs/FinanceOps/blob/master/04_Multi-Objective_Portfolio_Optimization.ipynb

My general comments:

1. The docs are quite good, but it took me forever to figure out to click "ALL" on your website so I was stuck on the "Quickstart" for a long time. Maybe you could rename the "ALL" button to "Manual" or "Docs"? And from the Quickstart page you should add a link to https://esa.github.io/pagmo2/docs/python/tutorials/python_tut.html as well, which is much better.

2. Error-messages are often impossible to understand because of the callbacks from the underlying C++ library, so you often don't know exactly where the problem is. For example, I experienced numerous problems with the fitness function returning incorrect values before I finally grasped that I always have to return a list. At one time I accidentally forgot to return anything so it defaults to returning `None` and that was also hard to figure out from the error-message.

Thanks again and I hope you can help with my question above.

**Comment by bluescarni** [comment] 2018-08-21 06:07
@Hvass-Labs Thanks for the comments!

Regarding the PSO parameters, perhaps @darioizzo or @CoolRunning can chime in as they are the algorithmic experts. See also #158 for proposed updates to PSO.

You can't find the ``/usr/local/include/pagmo/algorithms/pso.hpp`` file because that path refers to a C++ header that was used during the compilation of pygmo while producing the binary package, but the C++ files themselves are not shipped with pygmo. You can see the file online directly from the git repo here:

https://github.com/esa/pagmo2/blob/master/include/pagmo/algorithms/pso.hpp

Getting meaningful error messages from the underlying C++ code in Python is always challenging and a work in progress. I'll see if I can add some extra checks to the fitness function, since that is one of the most important functions.

Thanks also for the comments on the documentation, you are right that it is probably a good idea to point the users to the tutorials first and foremost.

**Comment by Hvass-Labs** [comment] 2018-08-21 06:30
Thanks for the detailed answer! I learned something from that :-)

I would suggest that you remove the parameter-bounds checks on the PSO altogether. You could give a warning instead, but it would be incorrect to e.g. warn people that negative parameters are bad. 

Furthermore, I am using pygmo (or is it pagmo? or pagmo2? :-) with so-called Meta-optimization (see https://en.wikipedia.org/wiki/Meta-optimization) and it would then give me a warning for each parameter set I would try, which would be annoying.

I had to move forward with my project so I decided just to use pygmo's DE optimizer instead. It also has bounds on the parameters, but they are less of a problem to me. E.g the crossover probability CR is enforced to be between 0 and 1 - which is correct. But the differential weight F is also enforced to be between 0 and 1 - but it is typically allowed to be between 0 and 2 in the literature, although I did find in my own work that best choices are usually below 1. So it's not a big deal but I think it would be a good idea to increase the bounds for F to between 0 and 2, so meta-optimization of the parameters would be more complete.

I'll let you know once I put my project on github as I think you will find it interesting.

Thanks again!

**Comment by bluescarni** [comment] 2018-08-24 21:27
Thanks for the explanation. I believe most of the other devs are on vacation right now, so it might take a week or so still before they can read/reply to your comments. I'll make sure to point them here, in case they miss the github notifications when they are overwhelmed by post-vacation mailbox syndrome :)

**Comment by bluescarni** [comment] 2018-08-28 10:15
pinging @darioizzo

**Comment by darioizzo** [comment] 2018-08-28 10:59
I would have to run some tests to see if negative values can really help, and that they cannot produce unexpected behaviours .... in principle I do not see any reason they would be any good if negative, on the other hand I also do not see any harm in allowing users to experiment. Bounds in [-4, 4] could probably be a good choice with the inertia factor in [-2,2] or just [-4,4] for everything.

At the moment the c++ docs are also wrong as they state a limit of [0,1] which is, instead [0, 4] (see https://github.com/esa/pagmo2/blob/master/include/pagmo/algorithms/pso.hpp#L187)

**Comment by darioizzo** [comment] 2018-08-28 11:01
For DE, sure we can also extend that limit (F in [0,1]), again I do not see why F should be > 1, but then .... who knows right?

**Comment by bluescarni** [comment] 2018-08-29 08:12
The PSO docs have been fixed (both C++ and Python) in #205.

**Comment by bluescarni** [comment] 2018-09-03 11:37
@darioizzo do you think you might have time one of these days to check out if the bounds can be extended? I believe ensuring they won't result into runtime errors would be enough for the time being.

**Comment by darioizzo** [comment] 2018-09-03 11:39
sure, that was my plan already .... I looked in the code and it does not seem runtime errors can be generated, but I want to check also experimentally .....

**Comment by Hvass-Labs** [comment] 2018-09-05 12:37
@darioizzo wrote:

> I would have to run some tests to see if negative values in PSO can really help, and that they cannot produce unexpected behaviours .... in principle I do not see any reason they would be any good if negative

I found that negative parameters worked significantly better for my implementation of PSO.

The purpose of meta-optimization as discussed in #214 is to find "optimal" choices of control parameters for a heuristic optimizer, without any human bias of what works and what doesn't.

If you want to do a very rigorous search for good control parameters, you could extend my meta-optimization code linked to in #214 to run PSO on e.g. an entire suite of benchmark problems in different dimensions. It should be fairly easy to implement (just a for-loop over the problems and either sum the resulting fitness, or create a multi-objective meta-optimizer where each meta-fitness measure is for a new benchmark problem). But it might take a week or more to run it :-)

Unfortunately I am not currently able to do this experiment, but I would be most curious to hear your results if you run it.

**Comment by darioizzo** [comment] 2019-01-28 09:50
On PSO: I would rather not allow negative values as far as we have something published that advocates for negative values. (for the time being this remains valid: https://www.researchgate.net/publication/324558373_Particle_Swarm_Optimization_A_survey_of_historical_and_recent_developments_with_hybridization_perspectives).

Same for DE. If you can point us to papers where these parameters are set to values outside of the allowed bounds it would be a motivation to change also in pagmo

Will close this for the time being. Reopen if new info is found/added.

**Closed by darioizzo** 2019-01-28 09:50 UTC

**Comment by Hvass-Labs** [comment] 2019-01-31 08:43
I wrote an entire PhD thesis on this subject and I also discussed this in #214, but I don't want to waste any more time on this discussion.

For the record, you could try running meta-optimization yourself for tuning the PSO parameters with the possibility of having negative parameters. You just need to do minor code modifications. I made 3 different versions of meta-optimization all using your library as the backend, as I previously explained in #214:

https://github.com/Hvass-Labs/MetaOps

PS: I browsed the paper you linked to and its discussion of PSO parameters is clearly outdated.

**Comment by darioizzo** [comment] 2019-01-31 09:01
Can you post then a "non outdated" peer-reviewed paper where negative parameters are found to be of use?

**Comment by Hvass-Labs** [comment] 2019-01-31 10:54
Can you find a paper that has actually tested negative parameters for the PSO and found them inferior?

The paper you linked to had a brief summary of van den Bergh's old PhD thesis (which I have actually read!) and the other usual mathematical "convergence analyses" of PSO parameters. It has been over a decade since I read them, but as I recall, they study two kinds of convergence: Convergence of the swarm - which is irrelevant because that does not prove it has found the optimum. And infinity-limit convergence to the optimum of the fitness function - which is also irrelevant because even a completely random search will converge to the optimum if given infinitely many trials. In other words: Those mathematical "analyses" for parameter selection are completely useless!

Here is a link to my PhD thesis that is almost a decade old, which rigorously tested PSO with negative parameters and found that they have superior performance:

http://www.hvass-labs.org/people/magnus/thesis/pedersen08thesis.pdf

My PSO variant may be slightly different from yours. But I am aware of other papers that come to the same conclusions regarding negative PSO parameters for other variants, but I no longer work in this field and honestly don't remember the paper titles.

Whether something is peer reviewed is completely irrelevant, because reviewers almost never check the implementation. You also cannot prove heuristics correct so it is quite possible that the implementation is broken or different from that described in the paper. It has happened several times that leading peer reviewed journals in this field have published papers that turned out to be incorrect so they had to be retracted. My PhD thesis gives an example of a state-of-the-art DE variant (at the time) where I obtained the source-code from the author and found that the implementation was very different from that described in the paper. In fact, the implementation was so bad and broken that I found it astonishing that its author was working as a computer science professor. But that is how low the standard is in this field.

I have given you a link to 3 Python Notebooks that you can test for yourself. All you have to do is modify them to use PSO instead of DE, and to allow negative parameter bounds in your library. Experimenting like this is called science. You should try it sometime instead of arrogantly shutting down suggestions from people who know a lot more about a subject than you do.

**Comment by darioizzo** [comment] 2019-01-31 11:44
Ok, I understand your point of view. Unfortunately we have a policy to implement and follow only peer-reviewed research or our own research.

We also welcome PRs, in which case we can test performances in the tests directly.
