### ISSUE TITLE
Get an issue when import pygmo as pg

### ISSUE THREAD

**Issue by joeyhungry** [esa/pagmo2#140] opened 2017-11-25 01:48 UTC
hello, I got an issue when I first used pygmo. and I don't know how to fix it.
<img width="1206" alt="2017-11-25 9 47 16" src="https://user-images.githubusercontent.com/28210089/33226301-a9d03a0c-d1c5-11e7-8ebb-8e135a51e34f.png">

**Comment by joeyhungry** [comment] 2017-11-25 01:49
the error occurs when importing pygmo as pg.

**Comment by darioizzo** [comment] 2017-11-26 08:37
How was pygmo installed? conda, pip or compiled? What platform are you on? (osx and bits)

**Comment by joeyhungry** [comment] 2017-12-01 05:40
Thanks for reply.
As was told in installation instruction, I installed the pygmo through
conda (macOS 10.13, python3.6)
I have checked that pygmo had been installed correctly.



I also install Pycharm to ensure that it’s not the software(previously I
use Spyder) that caused the issue.

So if there is any help, I have found some related solutions but don’t know
how to deal with it:

https://bugs.python.org/issue20891

Maybe it’s useful to you.



在 2017年11月26日 下午4:37:02, Dario Izzo (notifications@github.com) 写到:

How was pygmo installed? conda, pip or compiled? What platform are you on?
(osx and bits)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/esa/pagmo2/issues/140#issuecomment-346992866>, or mute
the thread

**Comment by darioizzo** [comment] 2017-12-01 08:03
Ok, interesting, we will try to reproduce the error on our high sierra system and see if there is an issue with the conda packages. So far you are the first user to raise an issue ...

**Comment by joeyhungry** [comment] 2017-12-03 05:35
Thanks a lot！


在 2017年12月1日 下午4:03:59, Dario Izzo (notifications@github.com) 写到:

Ok, interesting, we will try to reproduce the error on our high sierra
system and see if there is an issue with the conda packages. So far you are
the first user to raise an issue ...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/esa/pagmo2/issues/140#issuecomment-348428263>, or mute
the thread

**Comment by darioizzo** [comment] 2017-12-04 22:01
Here is what I get on my mac, after I activate a conda environment
```
conda install pygmo
Fetching packages ...
pagmo-2.6-0.ta 100% |#########################################################################| Time: 0:00:02 846.66 kB/s
pygmo-2.6-np11 100% |#########################################################################| Time: 0:00:08 422.12 kB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################################| 100%
(pagmo) Darios MacBook Pro:~ darioizzo$ ipython
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:31:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pygmo as pg

In [2]: pg.__version__
Out[2]: '2.6'
```

**Comment by darioizzo** [comment] 2017-12-13 08:02
any news here? can we close this?

**Comment by bluescarni** [comment] 2017-12-13 14:20
@darioizzo maybe you could try to import pygmo from a spyder session? My wild guess is that spyder (or the other IDE @joeyhungry mentions) is doing something special when starting the Python interpreter, which makes pygmo misbehave.

**Comment by darioizzo** [comment] 2017-12-13 14:25
@bluescarni Sure, I am not familiar with spyder , I will try to install it and import pygmo .... keep posted

**Comment by darioizzo** [comment] 2017-12-20 22:24
I have installed spyder and succesfully imported pygmo. No issues whatsoever on my osx
![screen shot 2017-12-20 at 23 23 23](https://user-images.githubusercontent.com/3327087/34231570-e01b24f2-e5dc-11e7-9b0c-74222254b348.png)

**Comment by joeyhungry** [comment] 2018-01-18 04:39
I reinstalled macOS, and can finally import pygmo with no issue. 🙏


在 2017年12月1日 下午4:03:59, Dario Izzo (notifications@github.com) 写到:

Ok, interesting, we will try to reproduce the error on our high sierra
system and see if there is an issue with the conda packages. So far you are
the first user to raise an issue ...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/esa/pagmo2/issues/140#issuecomment-348428263>, or mute
the thread

**Closed** 2018-01-21 13:33 UTC

**Comment by KishManani** [comment] 2018-04-26 06:39
I get the same error. I'm using a Mac. I conda installed pygmo in a conda virtual environment. When I run "import pygmo as pg" in an ipython session in the shell or on PyCharm I get the following error:

import pygmo as pg
Fatal Python error: take_gil: NULL tstate
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by darioizzo** [comment] 2018-04-26 06:47
Probably you also have some problem with the say you mix system python and conda python?
If you want us to help yu debugging your system you need to give us more info.

How did you install the conda environment? Once the environment is active can you import numpy, scipy, matplotlib etc .... ?

The more info the better :) In essence try to pin point the issue so that we can help. But as I said its likely you have some weird installation issues on osx ....

**Comment by KishManani** [comment] 2018-04-26 06:53
I think the issue is similar to: https://github.com/potassco/clingo/issues/79

I created a new environment with python 2.7 and that worked.

The conda environment was installed like: conda create -n py36 python=3.6 anaconda
