### ISSUE TITLE
[BUG] gaco hangs when initial population is outside bounds

### ISSUE THREAD

**Issue by jschueller** [esa/pagmo2#493] opened 2021-12-07 10:21 UTC
when some points of the initial population are outside the bounds and the objective tend to make it go outside,
gaco can hang:

```
#include <pagmo/algorithms/gaco.hpp>
#include <pagmo/population.hpp>
#include <pagmo/problems/rosenbrock.hpp>

using namespace pagmo;

struct problem1 {
    vector_double fitness(const vector_double &x) const
    {
        return {x[1]};
    }
    std::pair<vector_double, vector_double> get_bounds() const
    {
        return {{-1.5, -1.5}, {1.5, 1.5}};
    }
    vector_double::size_type get_nobj() const
    {
        return 1;
    }
};

int main()
{
  try {
    problem prob{problem1{}};

    population pop1{prob, 0, 0};
    int size = 100;
//     std::uniform_real_distribution<double> unif(-1.5, 1.5); // OK
    std::uniform_real_distribution<double> unif(-3., 3.);  // FREEZE
    std::default_random_engine re;
    for (int i=0; i<size; ++i)
    {
      vector_double x(2);
      x[0] = unif(re);
      x[1] = unif(re);
      pop1.push_back(x);
    }

    gaco user_algo1{10u};
    pop1 = user_algo1.evolve(pop1);

	}
	catch(const std::exception & exc) {
		std::cout << "ex="<<exc.what() <<std::endl;
		return 2;
	}
	return 0;
}
```
more generally, do we have to check is the population is inside the bounds before calling pagmo, or do the algorithms will manage to "jump" inside the bounds ?

**Comment by bluescarni** [comment] 2021-12-08 13:45
Any idea @Sceki ?

> more generally, do we have to check is the population is inside the bounds before calling pagmo, or do the algorithms will manage to "jump" inside the bounds ?

As I wrote in the other thread, what happens with out-of-bounds conditions is algorithm-dependent. But in any case it should never lead to a hang/crash, and if it does it's a bug.

**Comment by Sceki** [comment] 2021-12-08 14:48
I believe that the problem is that this `while` loop can be endless in case the initial population is out of bounds: https://github.com/esa/pagmo2/blob/master/src/algorithms/gaco.cpp#L855. 

I think there are two possibilities: either we avoid the while loop (i.e., the re-sampling until we satisfy the bounds) for the case in which the user decides that out-of-bounds solutions are acceptable, or we simply do not accept initial populations that are out of bounds.
In the former case, we would need to add a boolean flag (similar to the `cmaes` `force_bounds`one) and skip that while loop (i.e., the re-sampling) in case that is set to `true`. 

I am a bit busy these days, but I will try to fix it with a PR as soon as possible..

**Comment by bluescarni** [comment] 2021-12-09 09:07
> I believe that the problem is that this `while` loop can be endless in case the initial population is out of bounds: https://github.com/esa/pagmo2/blob/master/src/algorithms/gaco.cpp#L855.
> 
> I think there are two possibilities: either we avoid the while loop (i.e., the re-sampling until we satisfy the bounds) for the case in which the user decides that out-of-bounds solutions are acceptable, or we simply do not accept initial populations that are out of bounds. In the former case, we would need to add a boolean flag (similar to the `cmaes` `force_bounds`one) and skip that while loop (i.e., the re-sampling) in case that is set to `true`.
> 
> I am a bit busy these days, but I will try to fix it with a PR as soon as possible..

Cheers!

Do you think it helps algorithmic performance to allow for out-of-bounds individuals? If you think it does not, then I'd personally be more in favour of throwing, rather than adding another configuration parameter.

**Comment by Sceki** [comment] 2021-12-09 13:15
Indeed, another configuration parameter seems a bit too much, and if the bounds are chosen wide enough the performance should be the same, so I will just throw I guess :)

**Comment by jschueller** [comment] 2022-10-25 10:15
seems we have the kind of problem with mhaco and constraints

**Comment by jschueller** [comment] 2024-07-29 07:50
@Sceki any progress on this ?

**Comment by Sceki** [comment] 2024-07-29 13:44
@bluescarni we can close this.. done in #576  :)

**Closed** 2024-07-29 14:24 UTC
Labels: bug
