### ISSUE TITLE
windows and linux return different  results

### ISSUE THREAD

**Issue by adumasphi** [esa/pagmo2#259] opened 2019-03-27 14:30 UTC
Hi,
I am using Pygmo 2.10 either in windows (64 bit) or in linux (64 bit) and I noticed that I do not have the same result even if I set the same seed. The result is repeatable within linux or within windows but not identical between them. Is this behavior normal ?

Here is the tested code:

```python
import pygmo as pg
isl = pg.island(algo = pg.de(10, seed=1234), prob = pg.ackley(5),
                size=20, udi=pg.thread_island(), seed=1234)
isl.evolve()
isl.wait()
print(isl.get_population().champion_f)
```
- In linux, I have this result : [13.49305442]
- In windows, I have this result : [10.95535576]

Thanks,
Antoine

**Comment by bluescarni** [comment] 2019-03-27 14:42
@adumasphi pagmo uses the random number generators from the standard library, and I don't think those guarantee uniform behaviour across different operating systems.

(To be precise, I *believe* that at least some of the generators are guaranteed to generate the same sequence of integral values given the same seed, but the issue is that the *distributions* have implementation-specific behaviour).

**Comment by bluescarni** [comment] 2019-03-28 11:57
I'll go ahead and close this report, as pagmo2 is working as intended. Please re-open if needed.

**Closed by bluescarni** 2019-03-28 11:57 UTC
