### ISSUE TITLE
Add a check to hessian sparsity?

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo2#153] opened 2018-03-16 08:07 UTC
The following code in the UDP
```
    std::vector<sparsity_pattern> hessians_sparsity() const {
        return {
            {{0,0}, {1,1}},
            {{0,0}, {2,0}, {2,2}},
            {{}},
            {{}},
            {{}},
        };
    }
```
does not create exception upon ```pagmo::problem``` construction but maybe it should! The Hessian is not checked for entries such as ```{{}}``` which clearly the user may use to intend an empty hessian. The correct syntax for pagmo in that case would be ```{}```, otherwise pagmo will expect a size 1 hessian to be returned by ```hessians ``` so that, for example, the following user provided function would be incorrect:
```
    std::vector<vector_double> hessians(const vector_double &dv) const {
        return {
            {2, 4},
            {2, 2, 1},
            {},
            {},
            {}
        };
    }
```
and produce an error message when and if an algorithm would call hessisans:
```
where: /home/dario/.local/include/pagmo/problem.hpp, 2246
what: On the hessian no. 2: Components returned: 0, should be 1

```

**Comment by bluescarni** [comment] 2018-03-16 09:32
A sparsity pattern is a vector of pairs. So when one inits a sparsity pattern with the syntax ``{{}}``, what happens is that a vector of one value-initialized pair is created: ``[[0,0]]`` (because ``{}`` is *value initialisation*, and value initialisation for C++ integrals is equivalent to zero initialisation).

I don't see how we could detect such an occurrence (unless somehow repeated ``[[0,0]]`` patterns are invalid? Can't ever remember the details of the sparsity stuff...). Seems to me an unfortunate consequence of equating C++11's initialisation rules with vector-like initialisation (a-la python lists).

**Comment by bluescarni** [comment] 2018-03-16 09:36
One possible way to prevent that syntax from working would be to use, instead of ``std::pair``, a custom coded class which prohibits that type of initialization (but otherwise behaves exactly like ``std::pair``).

**Comment by darioizzo** [comment] 2018-03-16 09:40
Could we not check in here upon construction of a problem? https://github.com/esa/pagmo2/blob/master/include/pagmo/problem.hpp#L1215 ?

**Comment by darioizzo** [comment] 2018-03-16 09:41
Ah ok,  now I get your point a [0,0] is created

**Comment by darioizzo** [comment] 2018-03-16 09:43
The error is still well phrased when raised, but I was thinking to the possibility of detecting it in ```check_hessians_sparsity(hs);```
Now I understand why its impossible without changing drastically the representation of the sparisty ...

**Comment by bluescarni** [comment] 2018-03-16 09:56
Here's a demo of what I mean:

https://godbolt.org/g/suXAtx

(try changing ``sparsity_pattern1`` to ``sparsity_pattern2`` in the main function)

**Comment by darioizzo** [comment] 2018-03-16 10:13
Yeps. Nice solution, but I am not sure we want to override the std::pair .... there may be hidden consequences? Like that we have to implement a more complex my_pair class? Also we would need to have the python exp for my_pair ... Is it worth?

**Comment by bluescarni** [comment] 2018-03-16 10:27
Personally I don't think it's worth it. It's an unfortunate syntactic quirk, but I'd rather warn about it in the tutorial or something like that.

**Comment by bluescarni** [comment] 2018-08-31 15:10
Closing this for the time being, as we established it's not a bug and nobody wants to embark in re-implementing ``std::pair`` with the desired behaviour.

**Closed by bluescarni** 2018-08-31 15:10 UTC
