### ISSUE TITLE
"Fatal Python error: take_gil: NULL tstate" in python 3.6.6 on macOS 10.13.6

### ISSUE THREAD

**Issue by benmoseley** [esa/pagmo2#223] opened 2018-09-24 23:28 UTC
Installing pygmo on macOS 10.13.6 High Sierra with python 3.6.6 using 

`conda install -c conda-forge pygmo`

gives the following error
```
>>> import pygmo
Fatal Python error: take_gil: NULL tstate

Abort trap: 6
```

perhaps related to this question?: https://github.com/potassco/clingo/issues/79

**Comment by darioizzo** [comment] 2018-09-25 05:36
Thanks for reporting, I can only check on 10.13.4 and python 3.6.5, and all works fine.
We would need to investigate this further, but have currently no access to the exact version you are using. Do you have any further details that can help us? Maybe you can use the template below (cut and paste in your reply and substitute the relevant sections:

```
<br/>
Environment (<code>conda list</code>):
<details>


PASTE HERE THE RESULT OF conda list


</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>


PASTE HERE THE RESULT OF conda info


</details>
```

**Comment by benmoseley** [comment] 2018-09-25 11:28
Here's my output of `conda list` and `conda info`
```
$ conda list
# packages in environment at /Users/bmoseley/anaconda3/envs/pygmo:
#
# Name                    Version                   Build  Channel
ampl-mp                   3.1.0                h26a2512_1    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
boost                     1.67.0           py36h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24             py36_1001    conda-forge
cloudpickle               0.5.6                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
eigen                     3.3.5                h2d50403_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
ipopt                     3.12.11         blas_openblash1727795_0  [blas_openblas]  conda-forge
ipykernel                 4.9.0                    py36_0    conda-forge
ipyparallel               6.2.2                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1.20170329         hb402a30_2
libffi                    3.2.1                h475c297_4
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            3.0.1                h93005f0_2
libsodium                 1.0.16               h470a237_1    conda-forge
metis                     5.1.0                         3    conda-forge
mumps                     5.0.2           blas_openblash613969f_210  [blas_openblas]  conda-forge
ncurses                   6.1                  h0a44026_0
nlopt                     2.5.0            py36hf8a1672_0    conda-forge
numpy                     1.15.2          py36_blas_openblashd3ea46f_0  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
pagmo                     2.9                  hfc679d8_0    conda-forge
parso                     0.3.1                      py_0    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       10.0.1                   py36_0
prompt_toolkit            1.0.15                     py_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pygmo                     2.9              py36h5c5fb89_0    conda-forge
python                    3.6.6                hc167b69_0
python-dateutil           2.7.3                      py_0    conda-forge
pyzmq                     17.1.2           py36hae99301_0    conda-forge
readline                  7.0                  h1de35cc_5
scotch                    6.0.5                h9c0d707_1    conda-forge
setuptools                40.2.0                   py36_0
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.24.0               ha441bb4_0
tk                        8.6.8                ha441bb4_0
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.31.1                   py36_0
xz                        5.2.4                h1de35cc_4
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               hf3cbc9b_2

$ conda info

     active environment : pygmo
    active env location : /Users/bmoseley/anaconda3/envs/pygmo
            shell level : 1
       user config file : /Users/bmoseley/.condarc
 populated config files : /Users/bmoseley/.condarc
          conda version : 4.5.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /Users/bmoseley/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/bmoseley/anaconda3/pkgs
                          /Users/bmoseley/.conda/pkgs
       envs directories : /Users/bmoseley/anaconda3/envs
                          /Users/bmoseley/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by darioizzo** [comment] 2018-10-08 11:16
Still trying to reproduce the problem on my system. I was unable so far. Will try again after updating my os machine. ny more information can be useful.

**Comment by bluescarni** [comment] 2018-10-08 11:35
I have an idea for a possible solution, but until we can reproduce the issue we won't be able to understand if the fix works or not.

**Comment by darioizzo** [comment] 2018-10-08 18:50
I updated my machine to 10.13.6 with the new XCode and installed a new conda environment as follows:

```bash
conda create --name pagmo
conda install pagmo pygmo
```

Still cannot reproduce a problem.
```
(pagmo) Darios MacBook Pro:Documents darioizzo$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygmo
>>> 

```

Not sure whats going on here. But if we cannot reproduce, we cannot fix it :) @bluescarni  whats your idea?

**Comment by bluescarni** [comment] 2018-10-09 07:45
From the reports that were linked earlier, it seems this might have to do with the fact that, on OSX, we are linking pygmo.so to the Python library. This is not something which should be needed normally (as Python extension modules are opened via ``dlopen()``, no need for compile-time linking), but it seems to be necessary in practice on some platforms/OS combinations.

So that is where I would start. But I don't want to go through an entire release process on a hunch that this will fix things, so it would be best if we could test the fix out (or if the reporters could do it).

(there's an argument to be made to push this change through anyway as it would be the "correct" way, so I might look into it nevertheless...)

**Comment by bluescarni** [comment] 2018-11-14 12:05
@benmoseley #230 has a tentative implementation of a fix for this problem. This will be in the upcoming pagmo/pygmo 2.10 version. Any chance you could compile the latest git version to test if the fix actually solves the problem for you?

**Comment by bluescarni** [comment] 2019-01-04 10:36
pagmo/pygmo 2.10 have been released with the fix mentioned above. I will go ahead and close this report, please re-open if needed.

**Closed by bluescarni** 2019-01-04 10:36 UTC
