### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue 

### ISSUE THREAD

**Issue by taleslimaf** [esa/pagmo2#317] opened 2019-07-03 22:50 UTC
When I try this in some problems:
              pop = pg.population(prob, popsize)

this type error pops up:
              TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type numpy.float32
              In this part of the code: /pygmo/__init__.py", line 380, in _population_init
                            __original_population_init(self, prob_arg, size)

**Comment by bluescarni** [comment] 2019-07-04 05:16
It looks like ``popsize`` is of type ``float32``. Can you try to manually convert it to ``float``?

E.g.,

```
pop = pg.population(prob, float(popsize))
```

**Comment by volpatto** [comment] 2019-07-05 04:36
I got the same error. Let me explain my context. I need to define a unique API for several optimization different solvers (e.g., scipy, pygmo and etc). So I define the following in a part of my code (which can be improved, I know):

```python
import attr  # I use it to avoid Python's OOP boilerplates
import numpy as np
import types

@attr.s(auto_attribs=True)
class PygmoOptimizationProblemWrapper:
    objective_function: types.FunctionType
    bounds: list
    args: list = None

    def fitness(self, x):
        if self.args is None:
            return [self.objective_function(x)]
        else:
            return [self.objective_function(x, *self.args)]

    def get_bounds(self):
        return self._transform_bounds_to_pygmo_standard

    @property
    def _transform_bounds_to_pygmo_standard(self):
        bounds_numpy = np.array(self.bounds)
        lower_bounds = list(bounds_numpy[:, 0])
        upper_bounds = list(bounds_numpy[:, 1])
        return lower_bounds, upper_bounds
```
At first a glance, everything looks fine, since it defines the methods `fitness` and `get_bounds`, required by `pygmo` specifications.

Let's define a simple objective function for test purpose, say, Rosenbrock:

```python
def f_rosenbrock(x, a=100):
    """
    Define the benchmark Rosenbrock function.
    :param numpy.ndarray x:
        The function's argument array.
    :return:
        The evaluated function at the given input array.
    :rtype: float
    """
    dim = len(x)
    f = 0.0
    for i in range(dim-1):
        left_term = a * (x[i + 1] - x[i] * x[i]) * (x[i + 1] - x[i] * x[i])
        right_term = (1. - x[i]) * (1. - x[i])
        f += left_term + right_term
    return f
```

Now we instantiate it:

```python
problem_dimension = 2
bounds = problem_dimension * [[-6, 6]]
problem_wrapper = PygmoOptimizationProblemWrapper(
    objective_function=f_rosenbrock,
    bounds=bounds,
)
```
and try to solve it with self-adaptive DE (`pagmo::sade`):

```python
import pygmo as pg

algo = pg.algorithm(pg.sade(gen=500))
prob = pg.problem(problem_wrapper)
pop = pg.population(prob, 20)
pop = algo.evolve(pop)
```

It generates the output:
```console
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-e79cd65110b3> in <module>
      1 algo = pg.algorithm(pg.sade(gen=500))
----> 2 prob = pg.problem(problem_wrapper)
      3 pop = pg.population(prob, 20)
      4 pop = algo.evolve(pop)

TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type numpy.int64
```

Well, I tried to debug it. Deep copy stage seems to perform properly. Just after the copy stage, this error is raised. I failed in identify why this is happening (sorry). Could anyone please give me some advice in how  to get it working? What I'm missing?

Thanks in advance!

**Comment by bluescarni** [comment] 2019-07-05 06:39
@volpatto the problem is here:

```
TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type numpy.int64
```

In other words, there is a function somewhere in pygmo exposed from C++ which requires in input a value of type ``double``, but it is being invoked with a value of type ``numpy.int64`` instead. We should probably look into why numpy types are not properly translated to C++ types when crossing the boundary between Python and C++, but in the meantime explicitly converting the offending value to a Python ``float`` should fix the issue.

My guess it that the problem might be here:

```
bounds = problem_dimension * [[-6, 6]]
```

Here the bounds are defined as lists of integers, which will then be translated into numpy arrays of integers at some point. Try this instead:

```
bounds = problem_dimension * [[-6., 6.]]
```

**Comment by volpatto** [comment] 2019-07-05 11:41
Thanks, @bluescarni! Now it works. It was pretty simple after all.

**Comment by bluescarni** [comment] 2019-07-11 08:35
@taleslimaf I am closing this report for the time being, please re-open if the suggested fix does not work.

**Closed by bluescarni** 2019-07-11 08:35 UTC

**Comment by taleslimaf** [comment] 2019-07-12 02:38
> It looks like `popsize` is of type `float32`. Can you try to manually convert it to `float`?
> 
> E.g.,
> 
> ```
> pop = pg.population(prob, float(popsize))
> ```

This don't work. The popsize is a int value and it should be.
The solution didn't work for me, my bounds it's ok. 

My error:
TypeError: No registered converter was able to produce a C++ rvalue of type **double** from this Python object of type **numpy.float32**

I know that the problem isn't in the creation of the problem. The problem is in creating an the population:
> pop = pg.population(prob, popsize)

Let me explain my context to. I'm trying to find the best hyperparameters of some models with DE/GA/PSO. All models that I try works fine, less the KNN. 
The problem is that I don't know with var was the problem.

When I run for KNN and got error:
```
print(prob)
print(prob.get_bounds())
```
I got this:
```
Problem name: <class 'Optimizer.HyperparameterSearchProblem'>
        Global dimension:                       3
        Integer dimension:                      0
        Fitness dimension:                      1
        Number of objectives:                   1
        Equality constraints dimension:         0
        Inequality constraints dimension:       0
        Lower bounds: [1, 0, 1]
        Upper bounds: [15, 2, 6]

        Has gradient: false
        User implemented gradient sparsity: false
        Has hessians: false
        User implemented hessians sparsity: false

        Fitness evaluations: 0

        Thread safety: none

(array([1., 0., 1.]), array([15.,   2.,   6.]))

```
Changing only the model (DT) and parameters (but the same project structure):
```

Problem name: <class 'Optimizer.HyperparameterSearchProblem'>
        Global dimension:                       3
        Integer dimension:                      0
        Fitness dimension:                      1
        Number of objectives:                   1
        Equality constraints dimension:         0
        Inequality constraints dimension:       0
        Lower bounds: [1, 2, 2]
        Upper bounds: [16, 26, 26]

        Has gradient: false
        User implemented gradient sparsity: false
        Has hessians: false
        User implemented hessians sparsity: false

        Fitness evaluations: 0

        Thread safety: none

(array([1., 2., 2.]), array([16., 26., 26.]))
```

**Comment by bluescarni** [comment] 2019-07-12 06:43
> > It looks like `popsize` is of type `float32`. Can you try to manually convert it to `float`?
> > E.g.,
> > ```
> > pop = pg.population(prob, float(popsize))
> > ```
> 
> This don't work. The popsize is a int value and it should be.
> The solution didn't work for me, my bounds it's ok.
> 
> My error:
> TypeError: No registered converter was able to produce a C++ rvalue of type **double** from this Python object of type **numpy.float32**

Sorry that was a blunder on my side, you are obviously correct that the population size must be an ``int``.

Do you have any idea where the usage of ``numpy.float32`` (as opposed to Python ``float``) might come from within your problem's structure?

**Comment by bluescarni** [comment] 2019-07-12 06:46
Perhaps your problem is returning fitnesses computed in ``float32``? When you build a population passing in a number of individuals, pagmo will have to run fitness evaluations to assign fitnesses to the new individuals. If the fitnesses are returned as arrays of ``float32`` as opposed to ``float``, that might trigger some type conversion error when crossing the boundary between C++ and Python.

**Comment by taleslimaf** [comment] 2019-07-13 03:18
You found my problem. Thank you so much.
The code was like this:

```
for train_index, test_index in self.cv.split(self.X):
                ...
                y_pred = cv_clf.predict(X_test)
                value = self.metric(y_test, y_pred)
                result.append(value)
return [np.mean(result)]

```
But I don't know why, sometimes np.mean(result) could not be converted as required. 
The simples solution:

```
value = np.mean(result)
value = float(value)
return [value]
```
This fix the problem for me. Thank you again.
