### ISSUE TITLE
Malloc error running pykep2+pygmo2 example?

### ISSUE THREAD

**Issue by NigelPB** [esa/pagmo2#159] opened 2018-04-04 13:25 UTC
Hello

I hope this is the right place to submit this problem. I'm running Pykep 2.1 and Pygmo 2.6 on my MacBook Pro - installation was via Anaconda Navigator 1.8.2, and I'm running OSX 10.13.3. 

I'm managing to code some simple Pykep and Pygmo problems which seem to be working fine, but when running Pykep example 5 (Global optimization of a multiple gravity assist trajectory with one deep space manouvre per leg), I'm hitting a malloc problem that is generated after the call to the archipelago algorithm. I've copied the full output from my session below - the first four lines show my Python version and associated build information. Note that I am running the framework version of Python, (pythonw) as required in order to have a functioning matplotlib in the OSX installation.

The session hangs after the final error message is issued. There are 8 malloc errors, one per value of _n_ in the call to pg.archipelago (I've checked, and reducing n reduces the number of malloc errors). 

I'm not sure what other information might be useful to help identify the problem, but any suggestions would be gratefully received!

Thanks

Nigel

******
(astro) npb-lap2:Astrodynamics nigelbannister$ pythonw
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykep as pk
>>> pk.examples.run_example5()
Running a Self-Adaptive Differential Evolution Algorithm .... on 8 parallel islands
python(57434,0x7fff9e705340) malloc: *** error for object 0x7ffee6639cf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57436,0x7fff9e705340) malloc: *** error for object 0x7ffee15c7cf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57432,0x7fff9e705340) malloc: *** error for object 0x7ffee14a1cf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57431,0x7fff9e705340) malloc: *** error for object 0x7ffee1f16cf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57429,0x7fff9e705340) malloc: *** error for object 0x7ffeecdb7cf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57435,0x7fff9e705340) malloc: *** error for object 0x7ffee3dabcf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57430,0x7fff9e705340) malloc: *** error for object 0x7ffeef5aacf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
python(57433,0x7fff9e705340) malloc: *** error for object 0x7ffee2e7acf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by darioizzo** [comment] 2018-04-04 13:47
Interesting. We never covered this use case in our CI, so there maybe something is off with your python / pygmo interaction.


Some thoughts:
1) We normally use conda with python and matplotlib in our osx builds. How come this solution is not ok with you and you use pythonw ? Would it be a solution to use conda and the "normal" python?

2) To help, we need you to pinpoint if the problem is in pygmo, pykep or at the interface. Could you run some archipelagos in pygmo2 using a non pykep udp (use some simple python udp). If that works, your issue could be in the pykep/pygmo2 interface .... 

3)

**Comment by NigelPB** [comment] 2018-04-08 22:00
Hi Dario

Thanks for your reply and my apologies for the slow response.

I have to admit that I don't fully understand what is going on with the python vs pythonw issue. The reason I've been running pythonw is that when I try running under python, I obtain the error message copied after the **** below. The link contained in the message takes you to a page in which this issue is discussed in a little more detail - it seems to be a known problem in certain circumstances.

What has me really puzzled though, is that after your last reply, I updated conda and installed everything again. The result was that I could run Pykep and Pygmo under python with no issues. But today, having restarted my machine, the error message is back in the conda environment that was working OK. If I use pythonw, all is OK.

Clearly there's something going on with my system, so I need to investigate further and address your point (2) above. I'll do that later this month. For the moment, I'm preparing a talk for the 2nd ESA Space Education Symposium in Hungary next week, and I'm highlighting the usefulness of Pykep/Pygmo in it, so I'm pushing on generating some results under pythonw. Will post again when I get some further information.

Thanks again for your input

Nigel



**************
(astro) Nigels-MBP-106:Astrodynamics nigelbannister$ python npb_porkchop.py 
Traceback (most recent call last):
  File "npb_porkchop.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/Users/nigelbannister/anaconda3/envs/astro/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/nigelbannister/anaconda3/envs/astro/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/nigelbannister/anaconda3/envs/astro/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
(astro) Nigels-MBP-106:Astrodynamics nigelbannister$

**Comment by darioizzo** [comment] 2018-04-10 07:27
Nigel, I am not an osx guy, but after you install conda in osx, open a shell and try:

```
conda create -n pagmo python=3.6
source activate pagmo
conda install pygmo
python -c "import pygmo; pygmo.test.run_test_suite(1)"
```
This works in all our (OSX) virtual machines. 
Does it work on yours?

**Comment by darioizzo** [comment] 2018-05-24 06:42
closing this as user is not responding.

**Closed by darioizzo** 2018-05-24 06:42 UTC

**Comment by NigelPB** [comment] 2018-05-28 19:10
Hi Dario,

Please accept my apologies for the lack of response to your advice above. I've been pursuing this in down time between projects, and started writing a reply some time ago - but other things took over and I'm afraid I simply forgot that I'd not concluded this exchange. The email which arrived when you closed the issue was a useful prompt.

I followed your suggestions  - and yes; it works perfectly. I had to manually install Pykep, Scipy and Matplotlib (just using conda install) to run some of the other test codes, but that also proceeded without any problems - no issues with conflicting versions of Boost which I've seen previously.

This is great news and means we can start working again on some project work using Pygmo. Thank you again for your help - it is much appreciated, contrary to what the delayed reply may have suggested.

Best Regards

Nigel
