### ISSUE TITLE
pagmo Debug error

### ISSUE THREAD

**Issue by liudafei** [esa/pagmo2#343] opened 2019-09-13 15:05 UTC
pagmo version 2.11.3, install from conda

`problem prob{schwefel(30)};`

```
template <typename T, generic_ctor_enabler<T> = 0>
    explicit problem(T &&x)
        : m_ptr(detail::make_unique<detail::prob_inner<uncvref_t<T>>>(std::forward<T>(x))), m_fevals(0u), m_gevals(0u),
          m_hevals(0u)
    {
        generic_ctor_impl();// An unhandled exception: 0x00007FFDD171BC78 (ucrtbase.dll)
    }
```
This problem occurs when dealing with user-defined problems, also when dealing with native problems

**Comment by bluescarni** [comment] 2019-09-13 18:47
@liudafei would it be possible to see a minimal but complete example of the code producing the error?

The ``An unhandled exception`` message seems to be saying that an exception was thrown at some point, which does not necessarily indicate a bug.

**Comment by liudafei** [comment] 2019-09-14 01:55
@bluescarni 

When I run the "[Quick start](https://esa.github.io/pagmo2/quickstart.html)" example, the exception mentioned above will appear.

system: windows 10 1903
OS version: 18362.356
compiler: Microsoft Visual Studio Community 2019 16.1.6

Debug mode: abnormal running, the result would not show.
Release mode: normal running.

```
#include <iostream>

#pragma warning( disable: 4251 )
#include <pagmo/algorithm.hpp>
#include <pagmo/algorithms/sade.hpp>
#include <pagmo/archipelago.hpp>
#include <pagmo/problem.hpp>
#include <pagmo/problems/schwefel.hpp>
#pragma comment( lib, "pagmo.lib" )

using namespace pagmo;

int main()
{
  // 1 - Instantiate a pagmo problem constructing it from a UDP
  // (user defined problem).
  problem prob{schwefel(30)};// exception

  // 2 - Instantiate a pagmo algorithm
  algorithm algo{sade(100)};

  // 3 - Instantiate an archipelago with 16 islands having each 20 individuals
  archipelago archi{16u, algo, prob, 20u};

  // 4 - Run the evolution in parallel on the 16 separate islands 10 times.
  archi.evolve(10);

  // 5 - Wait for the evolutions to be finished
  archi.wait_check();

  // 6 - Print the fitness of the best solution in each island
  for (const auto& isl : archi)
  {
    std::cout << isl.get_population().champion_f()[0] << '\n';
  }
}
```

**Comment by bluescarni** [comment] 2019-09-14 12:44
@liudafei I believe the problem is that the pagmo conda package is compiled in ``Release`` mode.

My understanding is that MSVC does not like mixing together code which has been compiled in ``Release`` mode with code that has been compiled in ``Debug`` mode (especially C++ code).

I *think* that is is possible in principle to take appropriate steps in pagmo in order to ensure that such mixed-mode compilation works, but the problem is that none of us of the core team are MSVC users, thus it's hard for us to add this functionality.

**Comment by liudafei** [comment] 2019-09-14 13:37
@bluescarni 

Thank you for your help.

I understand the cause of this problem.

I will try compile pagmo  from source to solve this problem.

**Comment by bluescarni** [comment] 2019-09-14 13:50
@liudafei 

Keep in mind that if you want to have a functioning ``Debug`` build of pagmo, in principle you need to compile all its dependencies in ``Debug`` mode too.

Feel free to come over to our gitter channel if you have issues:

https://gitter.im/pagmo2/Lobby

**Comment by liudafei** [comment] 2019-09-14 14:58
@bluescarni 

Thanks!

I will give it a try.

**Comment by bluescarni** [comment] 2019-10-27 16:37
Will close this for the time being, please @liudafei re-open if needed.

**Closed by bluescarni** 2019-10-27 16:37 UTC
Labels: question
