### ISSUE TITLE
pygmo archipelago using simulated_annealing only improves the initial champion?

### ISSUE THREAD

**Issue by bsugerman** [esa/pagmo2#155] opened 2018-03-16 20:47 UTC
In using the simulated_annealing algorithm in an archipelago, I found that only the initial champion seems to be evolved and all the other islands stay the same. 

Consider the following test case:

`archi=pg.archipelago(n=1,algo=pg.de(),pop_size=10,prob=pg.rosenbrock(10),seed=32)`
`archi[0].get_population().get_f()`
`array([[ 1119502.9304024 ],
        [ 1887060.79044021],
        [  881859.7076029 ],
        [ 1103797.48649139],
        [  758181.03305512],
        [ 1747402.51182214],
        [ 1030352.91487772],
        [  416032.91483984],
        [ 1836179.29729704],
        [  609598.37469839]])`
` `
`archi.evolve(); archi.wait()`
`archi[0].get_population().get_f()`
`array([[  216007.47204985],
        [ 1270458.58395363],
        [  881859.7076029 ],
        [  276188.16879124],
        [  555552.67057929],
        [ 1265020.82538769],
        [  384033.30916346],
        [  360803.18304403],
        [ 1798444.20627363],
        [  230837.65916308]])`

But if I run the same using `algo=pg.simulated_annealing()`, then the evolved population_f after one call to `archi.evolve()` becomes,
 
`array([[  1.11950293e+06],
        [  1.88706079e+06],
        [  8.81859708e+05],
        [  1.10379749e+06],
        [  7.58181033e+05],
        [  1.74740251e+06],
        [  1.03035291e+06],
        [  6.23189001e+00],
        [  1.83617930e+06],
        [  6.09598375e+05]])`

Notice that only the island with the smallest fitness at the start has been evolved. But most of the fitness vectors change using `pg.de()`. This happens with different problems, different algorithms, and different numbers of islands. Seems like a bug?

So far the workaround I've found is to call 
`archi = pg.archipelago(n = 10, algo = pg.simulated_annealing(), prob = pg.rosenbrock(10), pop_size = 1, seed = 32)` instead. However, if I do this using `pg.de()` as the algo, I receive "**error occurred**" for each thread. Very odd, all of it...

**Comment by darioizzo** [comment] 2018-03-17 10:49
Nothing odd here. All is intended behavior.

There several problems with the use of the ```archipelago``` and the ```algorithm``` detailed above.

1) If you use the archipelago with ```pg.de``` and pop_size=1 the "**error occurred**" is to be expected as ```de``` is a population based algorithm and needs at least a population of size 4. 
2) When an archipelago raises error in the islands, you can inspect those exceptions by calling the ```wait_check``` method. See https://esa.github.io/pagmo2/docs/python/tutorials/using_archipelago.html#managing-exceptions. If you do so you will see that the exeption is likely to be "de needs at least 4 individuals ...."
3) Simulated annealing is not population based and, as documented, only evolves one selected individual in the population. Which is what the code above shows.
4) "Notice that only the island with the smallest fitness" should be "Notice that only the chromosome with the smallest fitness" -> Which is what sa is supposed to do.
5) " most of the fitness vectors change using pg.de()" -> again thats intended behaviour of de. Since the user only evolves for one generation (use of default parameters)

Will close this and let the user rethink what he is doing and in case ask for help in gitter.

**Closed by darioizzo** 2018-03-17 10:49 UTC

**Comment by bsugerman** [comment] 2018-03-17 18:43
Thanks for those explanations. I've read and re-read the documentation for c++ and python versions quite a few times, and never understood that an archipelago acts as you suggested. I'm sorry if I use the wrong terms here, but I understand that an archipelago is a collection of islands, and each island is a population of N potential solution vectors to a problem. I thought that evolving an archipelago was just a threaded/parallel way of evolving a population. So if I set up a population of size=96, it will create 96 test vectors for a problem, and then use the algorithm to minimize all 96 of them. I understood an archipelago of n=6 islands with pop_size=16 would also create 96 test vectors and minimize all 96 of them, but using 6 threads so it runs 6x faster. Instead, you seem to be saying that such an archipelago will create 96 test vectors but only evolve the lowest initial champion on each island, and leave the other 15 alone? 

Whether I'm right or not, I hope this indicates that the documentation may be missing some important information, or it may be placed in a non-obvious place, or stated in a confusing way.

**Comment by darioizzo** [comment] 2018-03-17 19:17
We are always happy to improve the documentation, If you point us exactly to bits that confused you we can consider rewording.

An archipelago is a set of islands, each containing a population. When evolving, the archipelago evolves the population in each island in parallel. To inspect the best individual in each isalnd you can write ```archi.get_champions_f()```, while your line above: ```archi[0].get_population().get_f()``` gets all the fitness vectors of the population living in the isalnd wth id 0.

Did you follow the many tutorial available in the web pages? In case you found confusing statements there too, let us know.

As for what individual evolves: its the whole population that evolves, but for non - population based algorithm (such as simulated annealing) one must pick one only individual.
